### ISSUE TITLE
不支持batch的批量推理代码的开发

### ISSUE THREAD

**Issue by qrsssh** [RapidAI/RapidLaTeXOCR#20]
您好， 非常感谢您的开源，看您的代码只支持单图的推理，是否考虑batch的批量推理代码的开发

**Comment by qrsssh** [comment]
@SWHL 多谢

**Comment by SWHL** [comment]
和[Discussions #19](https://github.com/RapidAI/RapidLaTeXOCR/discussions/19)重复了
